---
- name: Install java and net-tools
  become: true
  hosts: ec2
  tasks:
  - name: Pre-run | Update package cache (debian, etc)
    ansible.builtin.apt:
      update_cache: yes
      cache_valid_time: 3600
      name: "*"
      state: latest
  - name: Install Java 8 and net-tools
    apt:
      name:
        - openjdk-8-jre-headless
        - net-tools
      state: latest

- name: Download and unpack Nexus installer
  become: true
  hosts: ec2
  tasks:
    - name: Download Nexus
      get_url:
        url: https://download.sonatype.com/nexus/3/latest-unix.tar.gz
        dest: /opt/
      register: download_result
    - name: Untar Nexus Installer
      unarchive:
        src: "{{ download_result.dest }}"
        dest: /opt/
        remote_src: yes
      when: download_result.changed
    - name: Find Nexus folder
      find:
        paths: /opt/
        pattern: "nexus-*"
        file_type: directory
      register: find_result
    - name: Rename Nexus folder
      shell: mv {{ find_result.files[0].path }} /opt/nexus
      args:
        creates: /opt/nexus

- name: Create Nexus user to own Nexus folders
  become: true
  hosts: ec2
  tasks:
    - name: Ensure group nexus exists
      group:
        name: nexus
        state: present
    - name: Create nexus user
      user:
        name: nexus
        group: nexus
        groups: "nexus, sudo, admin"
        append: true
    - name: Make nexus user owner of nexus folder
      file:
        path: /opt/nexus
        state: directory
        owner: nexus
        group: nexus
        recurse: yes
    - name: Make nexus user owner of sonatype-work folder
      file:
        path: /opt/sonatype-work
        state: directory
        owner: nexus
        group: nexus
        recurse: yes

- name: Start Nexus with nexus user
  become: true
  hosts: ec2
  tasks:
    - name: Set run_as_user nexus
      lineinfile:
        path: /opt/nexus/bin/nexus.rc
        regexp: '^#run_as_user=""'
        line: run_as_user="nexus"
    - name: Start Nexus
      command: /opt/nexus/bin/nexus start

- name: Verify nexus running
  become: true
  hosts: ec2
  tasks:
    - name: Check with ps
      shell: ps aux | grep nexus
      register: app_status
    - debug: msg={{ app_status.stdout_lines }}
    - name: Wait one minute
      pause:
        minutes: 1
    - name: Check with netstat
      shell: netstat -plnt
      register: app_status
    - debug: msg={{ app_status.stdout_lines }}