---
- name: Create nginx web server
  become: true
  hosts: ec2
  tasks:
  - name: Pre-run | Update package cache (debian, etc)
    ansible.builtin.apt:
      update_cache: yes
      cache_valid_time: 3600
      name: "*"
      state: latest
  - name: Install nginx server
    apt:
      name: nginx
      state: absent
  - name: Start nginx server
    service:
      name: nginx
      state: stopped